import React, { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { PageHeader } from './BusinessPage';
import StatusBadge from '../components/StatusBadge';

export default function OfflineSyncPage(){
  const [pos,setPos]=useState(null); const [checking,setChecking]=useState(false);
  const check=async()=>{setChecking(true);try{const r=await api.posHealth();setPos({ok:r?.data?.status==='ok',data:r.data});}catch{setPos({ok:false});}finally{setChecking(false)}};
  useEffect(()=>{check();},[]);
  return <div className="page-stack"><PageHeader title="Offline & Sync" subtitle="See whether stores can keep selling when the internet or central Backend is unavailable." action={<button className="secondary-btn" onClick={check}><i className="bi bi-arrow-clockwise"/> {checking?'Checking…':'Check local POS'}</button>}/><div className="metric-grid"><SyncMetric icon="bi-hdd" title="SQLite durability" value="POSService-owned" status="partial"/><SyncMetric icon="bi-box-arrow-up" title="Outbox" value="Contract pending" status="contract"/><SyncMetric icon="bi-box-arrow-in-down" title="Inbox / change feed" value="Contract pending" status="contract"/><SyncMetric icon="bi-heart-pulse" title="Local health" value={pos?.ok?'Healthy':'Not detected'} status={pos?.ok?'live':'partial'}/></div><section className="panel"><div className="panel-title"><i className="bi bi-shield-check"/><div><h2>Offline readiness checklist</h2><p>Customer-friendly status; deep internals stay in Advanced Diagnostics.</p></div></div><div className="check-list"><Check ok={Boolean(pos?.ok)} title="Local POS service reachable" detail="GET /api/v1/health is available today."/><Check title="SQLite database healthy" detail="Requires POSService diagnostics endpoint."/><Check title="No failed local transactions" detail="Requires durable transaction health telemetry."/><Check title="Sync backlog within threshold" detail="Requires outbox summary endpoint."/><Check title="Recovery backup recent" detail="Requires backup status endpoint."/></div></section><section className="panel"><div className="panel-title"><i className="bi bi-arrow-left-right"/><div><h2>Required POSService management contract</h2><p>Endpoints the Hub expects as POSService matures.</p></div></div><div className="contract-grid">{[['GET','/api/v1/health','Live'],['GET','/api/v1/status','Service + SQLite + identity'],['GET','/api/v1/sync/status','Outbox/inbox/checkpoints'],['POST','/api/v1/sync/now','Manual sync'],['GET','/api/v1/devices','Hardware probes'],['GET','/api/v1/backups/status','Recovery readiness'],['POST','/api/v1/config/reload','Apply effective configuration'],['GET','/api/v1/version','Version/schema compatibility']].map(x=><div className="contract-row" key={x[1]}><code>{x[0]}</code><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div></section><section className="panel subtle"><StatusBadge status="contract"/><p className="mb0">The Hub deliberately keeps raw database and event internals out of normal customer views. Those belong in Advanced Diagnostics and SHAJTech support tooling.</p></section></div>;
}
function SyncMetric({icon,title,value,status}){return <div className="metric-card"><i className={`bi ${icon}`}/><div><span>{title}</span><strong>{value}</strong><StatusBadge status={status} compact/></div></div>}
function Check({ok,title,detail}){return <div className="check-row"><i className={`bi ${ok?'bi-check-circle-fill good-text':'bi-circle contract-text'}`}/><div><strong>{title}</strong><span>{detail}</span></div></div>}
