import React, { useEffect, useMemo, useState } from 'react';
import { api, unwrap } from '../lib/api';
import { inventoryApi } from '../lib/inventoryApi';
import '../styles/dashboard.css';

const emptyLine = () => ({ product_id: '', quantity: '1', purchase_price: '', selling_price: '', mrp: '', gst_percent: '0', batch_number: '', expiry_date: '' });
const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(Number(value || 0));
const errorMessage = (error, fallback) => error?.response?.data?.error?.message || error?.response?.data?.message || fallback;

export default function PurchaseEntryPage() {
  const [branches, setBranches] = useState([]), [suppliers, setSuppliers] = useState([]), [products, setProducts] = useState([]);
  const [branchId, setBranchId] = useState(''), [supplierId, setSupplierId] = useState(''), [invoiceNumber, setInvoiceNumber] = useState('');
  const [paymentMode, setPaymentMode] = useState('credit'), [paidAmount, setPaidAmount] = useState('0'), [lines, setLines] = useState([emptyLine()]);
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState(null);

  useEffect(() => { let active = true; Promise.all([api.branches(), inventoryApi.suppliers({ limit: 200 })]).then(([br, sr]) => { if (!active) return; const body = unwrap(br); const list = Array.isArray(body) ? body : (body?.branches || []); const sl = unwrap(sr, 'suppliers'); setBranches(list); setSuppliers(Array.isArray(sl) ? sl.filter((s) => s.is_active !== false) : []); if (list.length === 1) setBranchId(String(list[0].branch_id || list[0].id || '')); }).catch((e) => setError(errorMessage(e, 'Unable to load purchase references.'))).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  useEffect(() => { if (!branchId) { setProducts([]); return; } let active = true; inventoryApi.products({ branchId, limit: 100, sortBy: 'name', sortOrder: 'asc' }).then((r) => { if (active) { const list = unwrap(r, 'products'); setProducts(Array.isArray(list) ? list : []); } }).catch((e) => { if (active) setError(errorMessage(e, 'Unable to load products for this branch.')); }); return () => { active = false; }; }, [branchId]);

  const productMap = useMemo(() => new Map(products.map((p) => [String(p.id), p])), [products]);
  const estimatedTotal = useMemo(() => lines.reduce((sum, line) => { const q = Number(line.quantity), price = Number(line.purchase_price), gst = Number(line.gst_percent); if (!Number.isFinite(q) || !Number.isFinite(price) || q <= 0 || price < 0) return sum; const base = q * price; return sum + base + base * (Number.isFinite(gst) ? gst : 0) / 100; }, 0), [lines]);
  const updateLine = (index, key, value) => setLines((current) => current.map((line, i) => { if (i !== index) return line; if (key !== 'product_id') return { ...line, [key]: value }; const p = productMap.get(String(value)); return { ...line, product_id: value, purchase_price: String(p?.purchase_price ?? ''), selling_price: String(p?.selling_price ?? ''), mrp: String(p?.mrp ?? ''), gst_percent: String(p?.gst_percentage ?? 0), batch_number: '', expiry_date: '' }; }));

  const submit = async (event) => { event.preventDefault(); setError(''); setSuccess(null); if (!branchId) return setError('Select a store / branch.'); if (!supplierId) return setError('Select a supplier.'); const items = [];
    for (const line of lines) { const product = productMap.get(String(line.product_id)); const quantity = Number(line.quantity), purchasePrice = Number(line.purchase_price), sellingPrice = line.selling_price === '' ? undefined : Number(line.selling_price), mrp = line.mrp === '' ? undefined : Number(line.mrp), gst = Number(line.gst_percent || 0); if (!product) return setError('Every purchase line must select an existing Central product.'); if (!Number.isFinite(quantity) || quantity <= 0) return setError('Quantity must be greater than zero.'); if (!Number.isFinite(purchasePrice) || purchasePrice < 0) return setError('Purchase price must be zero or greater.'); if (!Number.isFinite(gst) || gst < 0 || gst > 100) return setError('GST must be between 0 and 100.'); if (product.is_batch_enabled && !line.batch_number.trim()) return setError(`Batch number is required for ${product.name}.`); items.push({ product_id: Number(product.id), quantity, purchase_price: purchasePrice, selling_price: sellingPrice, mrp, gst_percent: gst, batch_number: line.batch_number.trim() || undefined, expiry_date: line.expiry_date || undefined }); }
    const paid = Number(paidAmount || 0); if (!Number.isFinite(paid) || paid < 0) return setError('Paid amount must be zero or greater.'); setSaving(true); try { const response = await inventoryApi.createPurchase({ supplier_id: Number(supplierId), branch_id: branchId, invoice_number: invoiceNumber.trim() || null, payment_mode: paymentMode, paid_amount: paymentMode === 'credit' ? paid : undefined, items }); setSuccess(unwrap(response, 'purchase') || {}); setInvoiceNumber(''); setPaidAmount('0'); setLines([emptyLine()]); } catch (e) { setError(errorMessage(e, 'Purchase could not be recorded.')); } finally { setSaving(false); } };

  return <div className="page-stack dashboard-page"><section className="hero-panel"><div><span className="eyebrow">Inventory · Receiving</span><h1>Purchase Entry</h1><p>Receive supplier stock through the canonical Central purchase transaction. Central owns batches, stock movement, supplier payable and accounting postings.</p></div></section>{error && <div className="state-card bad" role="alert"><strong>Purchase not saved</strong><span>{error}</span></div>}{success && <div className="state-card"><strong>Purchase recorded</strong><span>Order #{success.order_id || 'created'} · Total {money(success.total_price)}</span></div>}
    <form className="page-stack" onSubmit={submit}><section className="panel"><div className="form-grid three-col"><label><span>Store / branch</span><select value={branchId} onChange={(e) => setBranchId(e.target.value)} disabled={loading}><option value="">Select branch</option>{branches.map((b) => { const id = b.branch_id || b.id; return <option key={id} value={id}>{b.branch_name || b.name || id}</option>; })}</select></label><label><span>Supplier</span><select value={supplierId} onChange={(e) => setSupplierId(e.target.value)}><option value="">Select supplier</option>{suppliers.filter((s) => !s.branch_id || !branchId || String(s.branch_id) === String(branchId)).map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span>Supplier invoice</span><input value={invoiceNumber} onChange={(e) => setInvoiceNumber(e.target.value)}/></label><label><span>Payment mode</span><select value={paymentMode} onChange={(e) => setPaymentMode(e.target.value)}><option value="credit">Credit</option><option value="cash">Cash</option><option value="bank">Bank</option><option value="online">Online</option></select></label>{paymentMode === 'credit' && <label><span>Paid now</span><input type="number" min="0" step="0.01" value={paidAmount} onChange={(e) => setPaidAmount(e.target.value)}/></label>}</div></section>
      <section className="panel"><h2>Received items</h2>{lines.map((line, index) => { const product = productMap.get(String(line.product_id)); return <div className="form-grid three-col" key={index}><label><span>Product</span><select value={line.product_id} onChange={(e) => updateLine(index, 'product_id', e.target.value)}><option value="">Select product</option>{products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{['quantity','purchase_price','selling_price','mrp','gst_percent'].map((key) => <label key={key}><span>{key.replaceAll('_',' ')}</span><input type="number" min="0" step="0.01" value={line[key]} onChange={(e) => updateLine(index, key, e.target.value)}/></label>)}<label><span>Batch number{product?.is_batch_enabled ? ' *' : ''}</span><input value={line.batch_number} onChange={(e) => updateLine(index, 'batch_number', e.target.value)}/></label><label><span>Expiry date</span><input type="date" value={line.expiry_date} onChange={(e) => updateLine(index, 'expiry_date', e.target.value)}/></label><button type="button" className="secondary-btn" onClick={() => setLines((c) => c.length === 1 ? c : c.filter((_, i) => i !== index))}>Remove line</button></div>; })}<div className="row-actions"><button type="button" className="secondary-btn" onClick={() => setLines((c) => [...c, emptyLine()])}>Add item</button><strong>Estimated total: {money(estimatedTotal)}</strong></div></section>
      <section className="panel dashboard-scope-note"><i className="bi bi-shield-check"/><div><strong>Inventory invariant</strong><span>RetailHub submits receiving facts only. Central validates branch/supplier/product ownership, creates or updates batches, increments canonical stock, records purchase items, supplier payable and ledger postings atomically.</span></div></section><button className="primary-btn" disabled={saving || loading}>{saving ? 'Recording purchase…' : 'Record purchase'}</button></form></div>;
}
