export const genericModules = {
  billing: { title:'Billing & Checkout', subtitle:'Control checkout behavior across stores and POS terminals.', sections:[['Sales rules',['Default sale mode','Default payment method','Discount policy','Negative-stock policy','Customer requirement']],['Product behavior',['Piece and weighted products','Barcode rules','Price override permission','Returns policy']],['Register operations',['Opening required','Closing required','Cash float','Manager approvals']]] },
  inventory: { title:'Inventory Policies', subtitle:'Define stock behavior once and inherit it across branches.', sections:[['Tracking',['Batch tracking','Expiry tracking','Weighted precision','Serial/lot tracking']],['Controls',['Negative inventory','Low-stock alerts','Reorder points','Stock adjustment permissions']],['Purchasing',['Valuation method','Purchase approval','Supplier defaults','Inter-branch transfers']]] },
  users: { title:'Users & Access', subtitle:'Role-based access for owners, managers, cashiers and back-office teams.', sections:[['Identity',['Invite users','Branch assignment','Device restrictions','Session management']],['Permissions',['Role templates','Fine-grained permissions','Manager approvals','Temporary access']],['Workforce',['Shift assignment','Cashier PIN','Attendance integration','Activity history']]] },
  payments: { title:'Payments', subtitle:'Configure accepted tenders, settlement and payment integrations.', sections:[['Tender types',['Cash','UPI','Card','Credit/customer ledger','Split payment']],['Providers',['PhonePe','Additional gateways','Terminal mapping','Provider health']],['Settlement',['Settlement reconciliation','Refund policy','Dispute tracking','Payout reports']]] },
  integrations: { title:'Integrations', subtitle:'Connect retail operations to external business systems.', sections:[['Current & near-term',['WhatsApp receipts','Payment providers','Accounting export','Printer bridge']],['Business systems',['ERP','E-commerce','Marketplace','CRM/loyalty']],['Data exchange',['Webhooks','Scheduled exports','Credentials management','Integration health']]] },
  security: { title:'Security & Audit', subtitle:'Protect the business and maintain a clear change history.', sections:[['Access',['Multi-factor authentication','Biometric/device lock','Session timeout','Trusted devices']],['Audit',['Settings history','User actions','POS overrides','Exportable audit trail']],['Risk',['Activity alerts','Failed login alerts','Emergency device revoke','Data retention']]] },
  notifications: { title:'Notifications', subtitle:'Route operational alerts to the right people without noise.', sections:[['Inventory',['Low stock','Expiring batches','Purchase due','Stock variance']],['Operations',['POS offline','Sync backlog','Printer disconnected','Shift not closed']],['Business',['Daily summary','High-value sale','Refund alert','Subscription notice']]] },
  data: { title:'Data & Backup', subtitle:'Control exports, retention, local backups and recovery readiness.', sections:[['Backup',['Local SQLite backup','Cloud backup policy','Restore verification','Retention windows']],['Lifecycle',['Export business data','Archive old records','Import history','Data quality checks']],['Recovery',['Recovery points','POS replacement flow','Schema migration status','Recovery drills']]] },
  automation: { title:'Automation', subtitle:'Future rules engine for repeatable retail operations.', sections:[['Rules',['Reorder automation','Price scheduling','Branch opening checks','Exception routing']],['Workflows',['Approval chains','Supplier follow-up','End-of-day jobs','Scheduled reports']],['Actions',['Notifications','Data exports','Integration tasks','Operational triggers']]] },
  'ai-insights': { title:'AI & Insights', subtitle:'Future intelligence layer built on governed retail data.', sections:[['Forecasting',['Demand forecast','Reorder suggestions','Expiry risk','Staffing insights']],['Copilot',['Business Q&A','Anomaly explanation','Daily briefing','Action recommendations']],['Governance',['Human approval','Explainability','Data boundaries','AI activity log']]] },
  commerce: { title:'Commerce Channels', subtitle:'Future omnichannel controls for store, online and marketplace sales.', sections:[['Channels',['Web store','Marketplace connectors','Click & collect','Delivery partners']],['Catalog',['Channel pricing','Availability rules','Images/content','Product mapping']],['Orders',['Unified order queue','Fulfilment routing','Returns','Customer notifications']]] },
  developer: { title:'Developer & API', subtitle:'Future extension surface for larger customers and partners.', sections:[['API',['Scoped access','Applications','Rate limits','API usage']],['Events',['Event subscriptions','Event explorer','Delivery retries','Signing configuration']],['Extensions',['Partner apps','Sandbox','Versioned contracts','Developer logs']]] }
};
